#!/bin/bash


if [ "x$1" = "xconfig" ]; then
	echo "graph_title Volume Group used space (in bytes)"
	echo "graph_args --base 1024 --lower-limit 0"
	echo "graph_vlabel bytes"
	echo "graph_category disk"
	echo "graph_total Total"
	vgs --noheadings | awk '{ print $1 ".label " $1 }'
	exit 0
fi

vgs --noheadings --units b --nosuffix | awk '{ print $1 ".value " $6-$7 }'
