#!/bin/sh

targets="sg2 sg3 sg4 sg5 sg6"

if [ "x$1" = "xconfig" ]; then
	cat << __EOF__
graph_title Disk temperature
graph_info Displays temperature on the SCSI disk $targets
graph_category disk
graph_vlabel Celsisus
__EOF__
	for target in $targets; do
		sg_logs -t /dev/$target | awk "/Reference temp/ { print \"$target.critical \" \$4 }"
		echo "$target.label $target"
	done
	exit
fi

for target in $targets; do
	sg_logs -t /dev/$target | awk "/Current temp/ { print \"$target.value \" \$4 }"
done
